application: collegecreepermatt
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: main.app